### PR TITLE
[It is SPAM] Portfolio html code

### PR DESCRIPTION
**Pull request by AryanSingh2410**

### CODE REVIEW

**Comment by airvzxf** [comment]
Are you serious that you want to merge this? Could you explain what is your logic?

**Comment by airvzxf** [comment]
Hey, @AryanSingh2410. Could you replay this message and explain to me why is your logic for this pull request?

**Comment by AryanSingh2410** [comment]
Please remove it as spam, it was uploaded by mistake.

**Comment by airvzxf** [comment]
@AryanSingh2410, this pull request sucks, it talks about your work as a professional and about yourself. Someone dirty, advantageous, unscrupulous, without intelligence. In your imagination, along with Barney and the Teletubis, you believed that putting your portfolio made you great and that you were going to have more scope for companies to hire you or someone to know of your insignificant existence. Is it that? I gave you the opportunity these days to explain to me the reason for your request, but nothing, you are not even man enough and mature enough to take responsibility for your actions and show your face.

**Pull request closed without merging**
